#ifndef __CONFIG_H__
#define __CONFIG_H__

//#define REGX_DEBUG

#define VLIB_REGX_LOGFILE	"/tmp/regx.log"
#define VLIB_SHM_BASE_KEY	0x52454758	/* regx */

#define VLIB_REGX_QUIT		(1 << 0)
#define VLIB_REGX_LD_FIN	(1 << 1)
typedef struct vlib_main_t {
	volatile int nr_sub_regx_proc;
	volatile uint64_t	nr__files;		/* total files. */
	volatile uint64_t	nr__size;		/* total size. */
	volatile uint64_t	nr_rx_files;	/* files that has been proccessed. */	
	volatile uint64_t	nr_rx_entries;
	volatile uint64_t	nr_rx_size;
	volatile uint64_t	nr_rx_err_skip_entries;
	time_t		epoch_time_sec_start;
	uint32_t	ul_flags;

} vlib_main_t;

#define regx_is_quit(vm)\
	(((vm)->ul_flags & VLIB_REGX_QUIT))

#define VLIB_REGX_S1AP_HANDOVER_HD\
	"len,msg_type,seq_id,frag,MF,offset,total_len,table_id,service_type,policy_id,start_time,cdr_id,device_id,filter_flag,data_type,cpu_clock_mul,sdr_id,cdr_type,handover_type,trigger_cause_type,trigger_cause,fail_cause_type,fail_cause,cancel_cause_type,cancel_cause,cancel_req_count,cancel_result,handover_req_count,cur_tac,cur_eci,cur_enbid,src_eci,src_enbid,src_tac,dest_tac,dest_eci,dest_enbid,mme_port,enodeb_port,mme_ip,enodeb_ip,mme_ue_s1apid,enb_ue_s1apid,mme_group_id,mme_code,ip_type,user_ipv4,user_ipv6,ue_maxbitrate_dl,ue_maxbitrate_ul,resp_delay,handover_delay,total_time,m_tmsi,imsi,calling,imei,apn,cdr_result,srvcc_ho_indication,msisdn_capability,handover_md5_hash,eps_bearer_number,Bearer_5_ID,Bearer_5_TYPE,Bearer_5_QCI,Bearer_5_Status,Bearer_5_Request_Cause,Bearer_5_Failure_Cause,Bearer_5_eNB_GTP_TEID,Bearer_5_SGW_GTP_TEID,Bearer_6_ID,Bearer_6_TYPE,Bearer_6_QCI,Bearer_6_Status,Bearer_6_Request_Cause,Bearer_6_Failure_Cause,Bearer_6_eNB_GTP_TEID,Bearer_6_SGW_GTP_TEID,Bearer_7_ID,Bearer_7_TYPE,Bearer_7_QCI,Bearer_7_Status,Bearer_7_Request_Cause,Bearer_7_Failure_Cause,Bearer_7_eNB_GTP_TEID,Bearer_7_SGW_GTP_TEID,Bearer_8_ID,Bearer_8_TYPE,Bearer_8_QCI,Bearer_8_Status,Bearer_8_Request_Cause,Bearer_8_Failure_Cause,Bearer_8_eNB_GTP_TEID,Bearer_8_SGW_GTP_TEID,Bearer_9_ID,Bearer_9_TYPE,Bearer_9_QCI,Bearer_9_Status,Bearer_9_Request_Cause,Bearer_9_Failure_Cause,Bearer_9_eNB_GTP_TEID,Bearer_9_SGW_GTP_TEID,Bearer_10_ID,Bearer_10_TYPE,Bearer_10_QCI,Bearer_10_Status,Bearer_10_Request_Cause,Bearer_10_Failure_Cause,Bearer_10_eNB_GTP_TEID,Bearer_10_SGW_GTP_TEID,Bearer_11_ID,Bearer_11_TYPE,Bearer_11_QCI,Bearer_11_Status,Bearer_11_Request_Cause,Bearer_11_Failure_Cause,Bearer_11_eNB_GTP_TEID,Bearer_11_SGW_GTP_TEID,Bearer_12_ID,Bearer_12_TYPE,Bearer_12_QCI,Bearer_12_Status,Bearer_12_Request_Cause,Bearer_12_Failure_Cause,Bearer_12_eNB_GTP_TEID,Bearer_12_SGW_GTP_TEID,Bearer_13_ID,Bearer_13_TYPE,Bearer_13_QCI,Bearer_13_Status,Bearer_13_Request_Cause,Bearer_13_Failure_Cause,Bearer_13_eNB_GTP_TEID,Bearer_13_SGW_GTP_TEID,Bearer_14_ID,Bearer_14_TYPE,Bearer_14_QCI,Bearer_14_Status,Bearer_14_Request_Cause,Bearer_14_Failure_Cause,Bearer_14_eNB_GTP_TEID,Bearer_14_SGW_GTP_TEID,Bearer_15_ID,Bearer_15_TYPE,Bearer_15_QCI,Bearer_15_Status,Bearer_15_Request_Cause,Bearer_15_Failure_Cause,Bearer_15_eNB_GTP_TEID,Bearer_15_SGW_GTP_TEID"
#define VLIB_REGX_S1AP_HANDOVER_SP_NUM	150

#define VLIB_REGX_WAP_HD\
	"len,msg_type,seq_id,frag,MF,offset,total_len,table_id,service_type,policy_id,start_time,cdr_id,device_id,filter_flag,data_type,cpu_clock_mul,sdr_id,trans_time,user_ip,mcc,mnc,eci_cell_id,tac,lac,rac,rat,uli,imsi,msisdn,imei,apn,charge_id,sgsn_u_ip,ggsn_u_ip,dest_ip,sgsn_u_teid,ggsn_u_teid,user_port,dest_port,tcp_fin_pkts,up_tcp_dropped_pkts,down_tcp_dropped_pkts,service_option,up_packets,down_packets,up_bytes,down_bytes,tcp_window_size,tcp_mss_size,tcp_reset_direction,proto_type,segment_flag,tcp_syn_pkts,tcp_conn_succ,tcp_syn_ack_pkts,tcp_ack_pkts,up_ip_frag_pkts,down_ip_frag_pkts,up_tcp_out_order_pkts,down_tcp_out_order_pkts,up_tcp_retrans_pkts,down_tcp_retrans_pkts,tcp_reset_pkts,direction,protocol_type,syn_synack_delay,synack_ack_delay,ack_first_data_delay,first_second_data_delay,nai,ha_ip,bsid,subnet,cdr_type,req_count,cause,content_length,resp_delay,dl_delay,last_ack_delay,version,wtp_abort_type,wtp_abort_reason,target_action,service_action_indicator,browser_tool,first_page_flag,user_agent,uri,host,x_online_host,content_type,referer,cookie,service_delay"
#define VLIB_REGX_WAP_SP_NUM 94

#define VLIB_REGX_EMM_HD\
	"len,msg_type,seq_id,frag,MF,offset,total_len,table_id,service_type,policy_id,start_time,cdr_id,device_id,filter_flag,data_type,cpu_clock_mul,sdr_id,cdr_type,msg_type,cause,ip_type,user_ipv4,user_ipv6,m_tmsi,mme_group_id,mme_code,req_count,mme_ue_s1ap_id,enb_ue_s1ap_id,mme_ip,enodeb_ip,mme_port,enodeb_port,cur_tac,src_tac,cur_eci,src_eci,mcc,mnc,paging_flag,ca_type,cdr_result,new_mme_code,uplink_count,downlink_count,resp_delay,total_time,imsi,calling,imei,apn,tmsi,lac,new_mme_group_id,new_m_tmsi,old_guti_type,msisdn_capability,paging_type,s1ap_cause_type,s1ap_cause,keyword2,rrc_establishment_cause,rand,autn,res,kasme"
#define VLIB_REGX_EMM_SP_NUM 65

#define VLIB_REGX_MME_HD\
	"len,msg_type,seq_id,frag,MF,offset,total_len,table_id,service_type,policy_id,start_time,cdr_id,device_id,filter_flag,data_type,cpu_clock_mul,sdr_id,cdr_type,msg_type,cause_type,cause,m_tmsi,mme_group_id,mme_code,ip_type,user_ipv4,user_ipv6,mme_ue_s1ap_id,enb_ue_s1ap_id,mme_ip,enodeb_ip,mme_port,enodeb_port,cur_eci,cur_tac,mcc,mnc,req_count,cdr_result,resp_delay,total_time,imsi,calling,imei,apn,uecontext_release_type,uecontext_release_cause,eps_bearer_number,Bearer_5_ID,Bearer_5_TYPE,Bearer_5_QCI,Bearer_5_Status,Bearer_5_Request_Cause,Bearer_5_Failure_Cause,Bearer_5_eNB_GTP_TEID,Bearer_5_SGW_GTP_TEID,Bearer_6_ID,Bearer_6_TYPE,Bearer_6_QCI,Bearer_6_Status,Bearer_6_Request_Cause,Bearer_6_Failure_Cause,Bearer_6_eNB_GTP_TEID,Bearer_6_SGW_GTP_TEID,Bearer_7_ID,Bearer_7_TYPE,Bearer_7_QCI,Bearer_7_Status,Bearer_7_Request_Cause,Bearer_7_Failure_Cause,Bearer_7_eNB_GTP_TEID,Bearer_7_SGW_GTP_TEID,Bearer_8_ID,Bearer_8_TYPE,Bearer_8_QCI,Bearer_8_Status,Bearer_8_Request_Cause,Bearer_8_Failure_Cause,Bearer_8_eNB_GTP_TEID,Bearer_8_SGW_GTP_TEID,Bearer_9_ID,Bearer_9_TYPE,Bearer_9_QCI,Bearer_9_Status,Bearer_9_Request_Cause,Bearer_9_Failure_Cause,Bearer_9_eNB_GTP_TEID,Bearer_9_SGW_GTP_TEID,Bearer_10_ID,Bearer_10_TYPE,Bearer_10_QCI,Bearer_10_Status,Bearer_10_Request_Cause,Bearer_10_Failure_Cause,Bearer_10_eNB_GTP_TEID,Bearer_10_SGW_GTP_TEID,Bearer_11_ID,Bearer_11_TYPE,Bearer_11_QCI,Bearer_11_Status,Bearer_11_Request_Cause,Bearer_11_Failure_Cause,Bearer_11_eNB_GTP_TEID,Bearer_11_SGW_GTP_TEID,Bearer_12_ID,Bearer_12_TYPE,Bearer_12_QCI,Bearer_12_Status,Bearer_12_Request_Cause,Bearer_12_Failure_Cause,Bearer_12_eNB_GTP_TEID,Bearer_12_SGW_GTP_TEID,Bearer_13_ID,Bearer_13_TYPE,Bearer_13_QCI,Bearer_13_Status,Bearer_13_Request_Cause,Bearer_13_Failure_Cause,Bearer_13_eNB_GTP_TEID,Bearer_13_SGW_GTP_TEID,Bearer_14_ID,Bearer_14_TYPE,Bearer_14_QCI,Bearer_14_Status,Bearer_14_Request_Cause,Bearer_14_Failure_Cause,Bearer_14_eNB_GTP_TEID,Bearer_14_SGW_GTP_TEID,Bearer_15_ID,Bearer_15_TYPE,Bearer_15_QCI,Bearer_15_Status,Bearer_15_Request_Cause,Bearer_15_Failure_Cause,Bearer_15_eNB_GTP_TEID,Bearer_15_SGW_GTP_TEID"
#define VLIB_REGX_MME_SP_NUM 135

#endif

